# Generated by Django 5.2.7 on 2025-11-01 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('component', 'Component'), ('product', 'Product')], max_length=32)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=32)),
                ('payload_before', models.JSONField(blank=True, null=True)),
                ('payload_after', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='product_management', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_management_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='product_man_entity__84221a_idx'), models.Index(fields=['created_at'], name='product_man_created_c8f2df_idx')],
            },
        ),
    ]
