# Generated by Django 5.2.7 on 2025-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningarticle',
            options={'ordering': ['custom_order', '-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='learningarticle',
            name='custom_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
