# Generated by Django 5.2.7 on 2025-10-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_tag_learningarticle_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningarticle',
            options={'ordering': ['-is_pinned', 'custom_order', '-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='learningarticle',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
