# Generated by Django 5.2.7 on 2025-10-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningarticle',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
