# Generated by Django 5.2.7 on 2025-10-24 23:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryVoltages',
            fields=[
                ('battery_voltage_value', models.IntegerField(unique=True)),
                ('battery_voltage_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'BatteryVoltages',
                'ordering': ['battery_voltage_value'],
            },
        ),
        migrations.CreateModel(
            name='ListingTypes',
            fields=[
                ('listing_type_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('listing_type_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'ListingTypes',
                'ordering': ['listing_type_name'],
            },
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('attribute_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('attribute_name', models.TextField(unique=True)),
                ('attribute_unit', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Attributes',
                'ordering': ['attribute_name'],
                'unique_together': {('attribute_name', 'attribute_unit')},
            },
        ),
        migrations.CreateModel(
            name='ItemCategories',
            fields=[
                ('item_category_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_category_name', models.TextField()),
                ('item_category_level', models.IntegerField(blank=True, null=True)),
                ('item_category_sortorder', models.IntegerField(blank=True, null=True)),
                ('item_category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.itemcategories')),
            ],
            options={
                'db_table': 'ItemCategories',
                'ordering': ['item_category_level', 'item_category_sortorder'],
                'unique_together': {('item_category_parent', 'item_category_name', 'item_category_level')},
            },
        ),
    ]
