# Generated by Django 5.2.7 on 2025-10-24 23:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('brand_name', models.TextField(unique=True)),
                ('brand_color', models.TextField(blank=True, null=True)),
                ('brand_logo', models.TextField(blank=True, null=True)),
                ('brand_sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Brands',
                'ordering': ['brand_sortorder'],
            },
        ),
    ]
