# Generated by Django 5.2.7 on 2025-10-24 23:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0002_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryPlatforms',
            fields=[
                ('battery_platform_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('battery_platform_name', models.TextField(unique=True)),
                ('battery_platform_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.brands')),
                ('battery_platform_voltage', models.ManyToManyField(to='toolanalysis.batteryvoltages')),
            ],
            options={
                'db_table': 'BatteryPlatforms',
                'ordering': ['battery_platform_name'],
            },
        ),
    ]
