# Generated by Django 5.2.7 on 2025-10-24 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0003_batteryplatforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailers',
            fields=[
                ('retailer_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('retailer_name', models.TextField(unique=True)),
                ('retailer_url', models.TextField(blank=True, null=True)),
                ('retailer_logo', models.TextField(blank=True, null=True)),
                ('retailer_sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Retailers',
                'ordering': ['retailer_sortorder'],
            },
        ),
    ]
