# Generated by Django 5.2.7 on 2025-10-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0004_retailers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtypes',
            name='listing_type_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.retailers'),
        ),
    ]
