# Generated by Django 5.2.7 on 2025-10-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0005_listingtypes_listing_type_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batteryplatforms',
            name='battery_platform_brand',
        ),
    ]
