# Generated by Django 5.2.7 on 2025-10-24 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0006_remove_batteryplatforms_battery_platform_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryplatforms',
            name='battery_platform_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.brands'),
        ),
    ]
