# Generated by Django 5.2.7 on 2025-10-25 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0007_batteryplatforms_battery_platform_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_sku', models.TextField(blank=True, null=True)),
                ('product_image', models.TextField(blank=True, null=True)),
                ('product_bullets', models.TextField(blank=True, null=True)),
                ('product_batteryplatform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.batteryplatforms')),
                ('product_batteryvoltage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.batteryvoltages')),
                ('product_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.brands')),
                ('product_itemcategory', models.ManyToManyField(to='toolanalysis.itemcategories')),
                ('product_listingtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.listingtypes')),
            ],
            options={
                'db_table': 'Products',
                'ordering': ['product_name'],
                'unique_together': {('product_brand', 'product_sku')},
            },
        ),
    ]
