# Generated by Django 5.2.7 on 2025-10-25 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0008_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='batteryplatforms',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='batteryvoltages',
            options={'ordering': ['value']},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'ordering': ['sortorder']},
        ),
        migrations.AlterModelOptions(
            name='itemcategories',
            options={'ordering': ['level', 'sortorder']},
        ),
        migrations.AlterModelOptions(
            name='listingtypes',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='retailers',
            options={'ordering': ['sortorder']},
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute_unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='batteryplatforms',
            old_name='battery_platform_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='batteryplatforms',
            old_name='battery_platform_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='batteryplatforms',
            old_name='battery_platform_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='batteryplatforms',
            old_name='battery_platform_voltage',
            new_name='voltage',
        ),
        migrations.RenameField(
            model_name='batteryvoltages',
            old_name='battery_voltage_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='batteryvoltages',
            old_name='battery_voltage_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='brand_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='brand_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='brand_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='brand_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='brand_sortorder',
            new_name='sortorder',
        ),
        migrations.RenameField(
            model_name='itemcategories',
            old_name='item_category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='itemcategories',
            old_name='item_category_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='itemcategories',
            old_name='item_category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='itemcategories',
            old_name='item_category_parent',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='itemcategories',
            old_name='item_category_sortorder',
            new_name='sortorder',
        ),
        migrations.RenameField(
            model_name='listingtypes',
            old_name='listing_type_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='listingtypes',
            old_name='listing_type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='listingtypes',
            old_name='listing_type_retailer',
            new_name='retailer',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_batteryplatform',
            new_name='batteryplatform',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_batteryvoltage',
            new_name='batteryvoltage',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_bullets',
            new_name='bullets',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_itemcategory',
            new_name='itemcategory',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_listingtype',
            new_name='listingtype',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_sku',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='retailers',
            old_name='retailer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='retailers',
            old_name='retailer_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='retailers',
            old_name='retailer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='retailers',
            old_name='retailer_sortorder',
            new_name='sortorder',
        ),
        migrations.RenameField(
            model_name='retailers',
            old_name='retailer_url',
            new_name='url',
        ),
        migrations.AlterUniqueTogether(
            name='attributes',
            unique_together={('name', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcategories',
            unique_together={('parent', 'name', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('brand', 'sku')},
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('batteryplatform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.batteryplatforms')),
                ('batteryvoltage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.batteryvoltages')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.brands')),
                ('itemcategory', models.ManyToManyField(to='toolanalysis.itemcategories')),
                ('listingtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.listingtypes')),
            ],
            options={
                'db_table': 'Components',
                'ordering': ['name'],
                'unique_together': {('brand', 'sku')},
            },
        ),
    ]
