# Generated by Django 5.2.7 on 2025-10-25 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0009_alter_attributes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Statuses',
                'ordering': ['sortorder'],
            },
        ),
        migrations.CreateModel(
            name='ComponentAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolanalysis.attributes')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.components')),
            ],
            options={
                'db_table': 'ComponentAttributes',
                'ordering': ['component', 'attribute'],
                'unique_together': {('component', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductAccessories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accessory', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.products')),
            ],
            options={
                'db_table': 'ProductAccessories',
                'ordering': ['product', 'quantity', 'accessory'],
                'unique_together': {('product', 'accessory')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolanalysis.attributes')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.products')),
            ],
            options={
                'db_table': 'ProductAttributes',
                'ordering': ['product', 'attribute'],
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductComponents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.components')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.products')),
            ],
            options={
                'db_table': 'ProductComponents',
                'ordering': ['product', 'component'],
                'unique_together': {('product', 'component')},
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.products')),
            ],
            options={
                'db_table': 'ProductImages',
                'ordering': ['product'],
                'unique_together': {('product', 'image')},
            },
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('specification', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.products')),
            ],
            options={
                'db_table': 'ProductSpecifications',
                'ordering': ['product', 'specification'],
                'unique_together': {('product', 'specification')},
            },
        ),
    ]
