# Generated by Django 5.2.7 on 2025-10-25 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0010_statuses_componentattributes_productaccessories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatusUpdates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.products')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.statuses')),
            ],
            options={
                'db_table': 'ProductStatusUpdates',
                'ordering': ['product', 'datetime'],
                'unique_together': {('product', 'datetime')},
            },
        ),
    ]
