# Generated by Django 5.2.7 on 2025-10-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0011_productstatusupdates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattributes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='product',
        ),
        migrations.DeleteModel(
            name='ComponentAttributes',
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
    ]
