# Generated by Django 5.2.7 on 2025-10-25 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0013_componentattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('batteryplatform', models.ManyToManyField(to='toolanalysis.batteryplatforms')),
                ('batteryvoltage', models.ManyToManyField(to='toolanalysis.batteryvoltages')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.brands')),
            ],
            options={
                'db_table': 'ProductLines',
                'ordering': ['name'],
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
