# Generated by Django 5.2.7 on 2025-10-25 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0014_productlines_delete_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.products')),
            ],
            options={
                'db_table': 'ProductImages',
                'ordering': ['product'],
                'unique_together': {('product', 'image')},
            },
        ),
    ]
