# Generated by Django 5.2.7 on 2025-10-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0015_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecifications',
            options={'ordering': ['product', 'name']},
        ),
        migrations.RenameField(
            model_name='productspecifications',
            old_name='specification',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='productspecifications',
            unique_together={('product', 'name')},
        ),
    ]
