# Generated by Django 5.2.7 on 2025-10-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0016_alter_productspecifications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productaccessories',
            options={'ordering': ['product', 'quantity', 'name']},
        ),
        migrations.RenameField(
            model_name='productaccessories',
            old_name='accessory',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='productaccessories',
            unique_together={('product', 'name')},
        ),
    ]
