# Generated by Django 5.2.7 on 2025-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0017_alter_productaccessories_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='batteryplatform',
        ),
        migrations.RemoveField(
            model_name='components',
            name='batteryvoltage',
        ),
        migrations.AddField(
            model_name='components',
            name='batteryplatform',
            field=models.ManyToManyField(to='toolanalysis.batteryplatforms'),
        ),
        migrations.AddField(
            model_name='components',
            name='batteryvoltage',
            field=models.ManyToManyField(to='toolanalysis.batteryvoltages'),
        ),
    ]
