# Generated by Django 5.2.7 on 2025-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0018_remove_components_batteryplatform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='batteryplatform',
            new_name='batteryplatforms',
        ),
        migrations.RenameField(
            model_name='components',
            old_name='batteryvoltage',
            new_name='batteryvoltages',
        ),
        migrations.RenameField(
            model_name='components',
            old_name='itemcategory',
            new_name='itemcategories',
        ),
        migrations.AddField(
            model_name='components',
            name='productlines',
            field=models.ManyToManyField(to='toolanalysis.productlines'),
        ),
    ]
