# Generated by Django 5.2.7 on 2025-10-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0019_rename_batteryplatform_components_batteryplatforms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='batteryplatform',
        ),
        migrations.RemoveField(
            model_name='products',
            name='batteryvoltage',
        ),
        migrations.AddField(
            model_name='products',
            name='batteryplatform',
            field=models.ManyToManyField(to='toolanalysis.batteryplatforms'),
        ),
        migrations.AddField(
            model_name='products',
            name='batteryvoltage',
            field=models.ManyToManyField(to='toolanalysis.batteryvoltages'),
        ),
    ]
