# Generated by Django 5.2.7 on 2025-10-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0020_remove_products_batteryplatform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='batteryplatform',
            new_name='batteryplatforms',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='batteryvoltage',
            new_name='batteryvoltages',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='itemcategory',
            new_name='itemcategories',
        ),
    ]
