# Generated by Django 5.2.7 on 2025-10-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0021_rename_batteryplatform_products_batteryplatforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='attributes',
            field=models.ManyToManyField(to='toolanalysis.attributes'),
        ),
    ]
