# Generated by Django 5.2.7 on 2025-10-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0022_components_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='attributes',
        ),
    ]
