# Generated by Django 5.2.7 on 2025-10-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0023_remove_components_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='statusupdates',
            field=models.ManyToManyField(to='toolanalysis.productstatusupdates'),
        ),
    ]
