# Generated by Django 5.2.7 on 2025-10-25 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0024_products_statusupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatusupdates',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
