# Generated by Django 5.2.7 on 2025-10-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0025_alter_productstatusupdates_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='statusupdates',
        ),
        migrations.AddField(
            model_name='products',
            name='discontinueddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='releasedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.statuses'),
        ),
        migrations.DeleteModel(
            name='ProductStatusUpdates',
        ),
    ]
