# Generated by Django 5.2.7 on 2025-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0026_remove_products_statusupdates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='name',
            field=models.TextField(),
        ),
    ]
