# Generated by Django 5.2.7 on 2025-10-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0027_alter_attributes_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentAttributes',
        ),
    ]
