# Generated by Django 5.2.7 on 2025-10-25 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0028_delete_componentattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.attributes')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.components')),
            ],
            options={
                'db_table': 'ComponentAttributes',
                'ordering': ['component', 'attribute'],
                'unique_together': {('component', 'attribute', 'value')},
            },
        ),
    ]
