# Generated by Django 5.2.7 on 2025-10-26 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0029_componentattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategoryAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('attribute', models.ManyToManyField(to='toolanalysis.attributes')),
                ('itemcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.itemcategories')),
            ],
            options={
                'db_table': 'ItemCategoryAttributes',
                'ordering': ['itemcategory'],
            },
        ),
    ]
