# Generated by Django 5.2.7 on 2025-10-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0030_itemcategoryattributes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCategoryAttributes',
        ),
    ]
