# Generated by Django 5.2.7 on 2025-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0031_delete_itemcategoryattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategories',
            name='attributes',
            field=models.ManyToManyField(to='toolanalysis.attributes'),
        ),
    ]
