# Generated by Django 5.2.7 on 2025-10-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0032_itemcategories_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='fair_price_narrative',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
