# Generated by Django 5.2.7 on 2025-10-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0033_components_fair_price_narrative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategories',
            options={'ordering': ['level', 'sortorder', 'name']},
        ),
    ]
