# Generated by Django 5.2.7 on 2025-10-28 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0034_alter_itemcategories_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Categories',
                'ordering': ['sortorder', 'name'],
            },
        ),
    ]
