# Generated by Django 5.2.7 on 2025-10-28 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0035_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('fullname', models.TextField(unique=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='toolanalysis.categories')),
            ],
            options={
                'db_table': 'Subcategories',
                'ordering': ['sortorder', 'name'],
            },
        ),
    ]
