# Generated by Django 5.2.7 on 2025-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0037_itemtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='categories',
            field=models.ManyToManyField(to='toolanalysis.categories'),
        ),
        migrations.AddField(
            model_name='components',
            name='itemtypes',
            field=models.ManyToManyField(to='toolanalysis.itemtypes'),
        ),
        migrations.AddField(
            model_name='components',
            name='subcategories',
            field=models.ManyToManyField(to='toolanalysis.subcategories'),
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(to='toolanalysis.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='itemtypes',
            field=models.ManyToManyField(to='toolanalysis.itemtypes'),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategories',
            field=models.ManyToManyField(to='toolanalysis.subcategories'),
        ),
    ]
