# Generated by Django 5.2.7 on 2025-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0038_components_categories_components_itemtypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='fullname',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
