# Generated by Django 5.2.7 on 2025-10-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0039_categories_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
