# Generated by Django 5.2.7 on 2025-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0040_components_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='showcase_priority',
            field=models.IntegerField(default=0, help_text='Higher priority = appears first in browse page sections'),
        ),
    ]
