# Generated by Django 5.2.7 on 2025-10-28 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0041_add_showcase_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtypes',
            name='attributes',
            field=models.ManyToManyField(to='toolanalysis.attributes'),
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Features',
                'ordering': ['sortorder', 'name'],
                'unique_together': {('name', 'value')},
            },
        ),
    ]
