# Generated by Django 5.2.7 on 2025-10-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0042_itemtypes_attributes_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='features',
            field=models.ManyToManyField(to='toolanalysis.features'),
        ),
    ]
