# Generated by Django 5.2.7 on 2025-10-28 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0043_components_features'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='features',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.RemoveField(
            model_name='features',
            name='value',
        ),
        migrations.CreateModel(
            name='ComponentFeatures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.components')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.features')),
            ],
            options={
                'db_table': 'ComponentFeatures',
                'ordering': ['component', 'feature'],
                'unique_together': {('component', 'feature', 'value')},
            },
        ),
    ]
