# Generated by Django 5.2.7 on 2025-10-28 21:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0044_alter_features_unique_together_alter_features_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MotorTypes',
                'ordering': ['sortorder', 'name'],
            },
        ),
    ]
