# Generated by Django 5.2.7 on 2025-10-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0045_motortypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='motortype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolanalysis.motortypes'),
        ),
        migrations.AddField(
            model_name='products',
            name='motortype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolanalysis.motortypes'),
        ),
    ]
