# Generated by Django 5.2.7 on 2025-10-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0046_components_motortype_products_motortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='features',
            field=models.ManyToManyField(to='toolanalysis.features'),
        ),
    ]
