# Generated by Django 5.2.7 on 2025-10-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0047_products_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='itemcategories',
        ),
        migrations.RemoveField(
            model_name='products',
            name='itemcategories',
        ),
    ]
