# Generated by Django 5.2.7 on 2025-10-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0048_remove_components_itemcategories_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcategories',
            unique_together={('name', 'level')},
        ),
        migrations.RemoveField(
            model_name='itemcategories',
            name='parent',
        ),
    ]
