# Generated by Django 5.2.7 on 2025-10-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0049_alter_itemcategories_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCategories',
        ),
    ]
