# Generated by Django 5.2.7 on 2025-10-28 23:43

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0050_delete_itemcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.TextField(default='USD')),
                ('url', models.TextField(blank=True, null=True)),
                ('datepulled', models.DateField(default=datetime.datetime.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.products')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.retailers')),
            ],
            options={
                'db_table': 'PriceListings',
                'ordering': ['retailer', 'product', 'datepulled'],
                'unique_together': {('retailer', 'product', 'price', 'datepulled')},
            },
        ),
    ]
