# Generated by Django 5.2.7 on 2025-10-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0051_pricelistings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricelistings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricelistings',
            name='retailer_sku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistings',
            unique_together={('retailer', 'product', 'retailer_sku', 'price', 'datepulled')},
        ),
    ]
