# Generated by Django 5.2.7 on 2025-10-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0052_alter_pricelistings_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='components',
            options={'ordering': ['name'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
    ]
