# Generated by Django 5.2.7 on 2025-10-29 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0053_alter_components_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated price from PriceListings', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='last_calculated_date',
            field=models.DateTimeField(blank=True, help_text='When the calculated price was last updated', null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='manual_override_note',
            field=models.TextField(blank=True, help_text='Reason for manual price override'),
        ),
        migrations.AddField(
            model_name='components',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual override price for this component', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='price_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='components',
            name='price_source_pricelisting',
            field=models.ForeignKey(blank=True, help_text='Specific price listing used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components_priced_from', to='toolanalysis.pricelistings'),
        ),
        migrations.AddField(
            model_name='components',
            name='price_source_product',
            field=models.ForeignKey(blank=True, help_text='Standalone product used for pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components_priced_from', to='toolanalysis.products'),
        ),
        migrations.AddField(
            model_name='components',
            name='use_manual_price',
            field=models.BooleanField(default=False, help_text='Use manual price instead of calculated price'),
        ),
        migrations.CreateModel(
            name='ComponentPricingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_type', models.CharField(choices=[('standalone', 'Standalone Product'), ('prorated', 'Prorated from Bundle'), ('manual', 'Manual Override')], max_length=20)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional calculation details', null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_history', to='toolanalysis.components')),
                ('source_pricelisting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolanalysis.pricelistings')),
                ('source_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolanalysis.products')),
            ],
            options={
                'db_table': 'ComponentPricingHistory',
                'ordering': ['-calculation_date'],
                'indexes': [models.Index(fields=['component', '-calculation_date'], name='ComponentPr_compone_d76473_idx')],
            },
        ),
    ]
