# Generated by Django 5.2.7 on 2025-10-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0054_components_calculated_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'ordering': ['sortorder', 'name']},
        ),
        migrations.AddField(
            model_name='attributes',
            name='sortorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
