# Generated by Django 5.2.7 on 2025-10-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0055_alter_attributes_options_attributes_sortorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
