# Generated by Django 5.2.7 on 2025-10-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0056_attributes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='standalone_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
