# Generated by Django 5.2.7 on 2025-10-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0057_components_standalone_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='calculated_price',
        ),
        migrations.RemoveField(
            model_name='components',
            name='last_calculated_date',
        ),
        migrations.RemoveField(
            model_name='components',
            name='manual_override_note',
        ),
        migrations.RemoveField(
            model_name='components',
            name='manual_price',
        ),
        migrations.RemoveField(
            model_name='components',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='components',
            name='price_source_pricelisting',
        ),
        migrations.RemoveField(
            model_name='components',
            name='price_source_product',
        ),
        migrations.RemoveField(
            model_name='components',
            name='use_manual_price',
        ),
    ]
