# Generated by Django 5.2.7 on 2025-10-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0058_remove_components_calculated_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentfeatures',
            unique_together={('component', 'feature')},
        ),
    ]
