# Generated by Django 5.2.7 on 2025-10-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0059_alter_componentfeatures_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='isaccessory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='isaccessory',
            field=models.BooleanField(default=False),
        ),
    ]
