# Generated by Django 5.2.7 on 2025-10-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0061_alter_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='displayformat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
