# Generated by Django 5.2.7 on 2025-10-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0062_attributes_displayformat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributes',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
