# Generated by Django 5.2.7 on 2025-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0063_alter_attributes_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailers',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
