# Generated by Django 5.2.7 on 2025-10-31 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0064_retailers_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolanalysis.statuses'),
        ),
    ]
