# Generated by Django 5.2.7 on 2025-11-01 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0065_alter_products_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentClasses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ComponentClasses',
                'ordering': ['sortorder', 'name'],
            },
        ),
    ]
