# Generated by Django 5.2.7 on 2025-11-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolanalysis', '0066_componentclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='componentclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolanalysis.componentclasses'),
        ),
        migrations.AlterField(
            model_name='components',
            name='listingtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolanalysis.listingtypes'),
        ),
    ]
