# Generated by Django 5.2.7 on 2025-10-30 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='componentaudit',
            new_name='components__compone_31ea43_idx',
            old_name='comp_compid_created_idx',
        ),
        migrations.RenameIndex(
            model_name='componentaudit',
            new_name='components__field_5ca83c_idx',
            old_name='comp_field_idx',
        ),
        migrations.AlterField(
            model_name='componentaudit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
